import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { myName } from "@/src/services/datya-provider";
import Navbar from "@/src/components/navbar/navbar";
import Home from "@/src/components/page-elements/home";
import About from "@/src/components/page-elements/about";

const inter = Inter({ subsets: ["latin"] });

export default function Main() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" relative ">
        <Navbar />
        <Home />
        <About/>
      </div>
    </>
  );
}
