import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" lg:hidden flex justify-center items-center h-screen ">
        <h1 className=" text-red-600 text-4xl md:text-5xl lg:text-8xl ">
          hello world
        </h1>
      </div>
    </>
  );
}
